---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.1
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: npm
    image: node:18-alpine
    commands:
      - npm ci --unsafe-perm

  - name: deployment
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: help_host
      username:
        from_secret: help_username
      port: 22
      key:
        from_secret: help_key
      script:
        - cd /home/help/website
        - bin/console update:server
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache
---
kind: signature
hmac: 3cfa48195a5c2f349f18cb499ab1fe4d6b35e9935f602601c67fe3df23831161

...
